# Generated by Django 3.0.9 on 2020-08-29 21:09

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.PositiveSmallIntegerField(default=0)),
                ('serving_size', models.PositiveSmallIntegerField(default=100)),
                ('image', models.ImageField(null=True, upload_to=core.models.food_picture_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseFood')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(default=0)),
                ('ingredients', models.ManyToManyField(to='core.FoodAmount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('calories', models.PositiveSmallIntegerField(default=0)),
                ('water_glasses', models.PositiveSmallIntegerField(default=0)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='core.Meal')),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diner', to='core.Meal')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='core.Meal')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack', to='core.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('basefood_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseFood')),
                ('instructions', models.TextField(blank=True)),
                ('ingredients', models.ManyToManyField(to='core.FoodAmount')),
            ],
            bases=('core.basefood',),
        ),
    ]
