# Generated by Django 3.0.9 on 2020-08-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200830_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
