# Generated by Django 3.0.9 on 2020-08-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200830_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefood',
            name='is_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodamount',
            name='belongs_to_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_contents', to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='foodamount',
            name='belongs_to_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.Recipe'),
        ),
        migrations.AlterField(
            model_name='foodamount',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseFood'),
        ),
    ]
