# Generated by Django 3.0.9 on 2020-08-30 10:47

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200830_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.food_picture_file_path),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='diner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diner', to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snack', to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_picture_file_path),
        ),
    ]
