# Generated by Django 3.0.9 on 2020-08-30 11:40

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200830_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.PositiveSmallIntegerField(default=0)),
                ('goal_weight', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('neck', models.PositiveSmallIntegerField(default=0)),
                ('chest', models.PositiveSmallIntegerField(default=0)),
                ('biceps', models.PositiveSmallIntegerField(default=0)),
                ('forearm', models.PositiveSmallIntegerField(default=0)),
                ('abdomen', models.PositiveSmallIntegerField(default=0)),
                ('hips', models.PositiveSmallIntegerField(default=0)),
                ('thigh', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.measurement_picture_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
